=== Fourmilab/hackers_diet_online/src/hackersdiet.dtd
<!--              The Hacker's Diet Online
            http://www.fourmilab.ch/hackdiet/online/

             XML Database Document Type Definition

    This definition is cited with a:
        <!DOCTYPE hackersdiet SYSTEM
            "http://www.fourmilab.ch/hackdiet/online/hackersdiet.dtd">
    declaration in compliant XML files.

-->

    <!-- Root element -->

    <!ELEMENT hackersdiet
        (epoch?, account?, monthlogs?)
    >

    <!ATTLIST hackersdiet
        version     CDATA   #REQUIRED
    >

    <!ELEMENT epoch                 (#PCDATA)>

    <!ELEMENT account
        (user?, preferences?, diet-plan?)
    >

    <!ATTLIST account
        version     CDATA   #REQUIRED
    >

    <!ELEMENT monthlogs
        (monthlog*)
    >

    <!ATTLIST monthlogs
        version     CDATA   #REQUIRED
    >

    <!-- User information.  This element is optional but,
         if present, must be first in the file. -->

    <!ELEMENT user
        (login-name?,
         first-name?,
         middle-name?,
         last-name?,
         e-mail?,
         height?,
         account-created?)
    >

    <!ATTLIST user
        version     CDATA   #REQUIRED
    >

    <!ELEMENT login-name            (#PCDATA)>
    <!ELEMENT first-name            (#PCDATA)>
    <!ELEMENT middle-name           (#PCDATA)>
    <!ELEMENT last-name             (#PCDATA)>
    <!ELEMENT e-mail                (#PCDATA)>
    <!ELEMENT height                (#PCDATA)>
    <!ELEMENT account-created       (#PCDATA)>

    <!-- Preferences.  This element is optional but,
         if present, must be after the user information,
         if present.  -->

    <!ELEMENT preferences
        (log-unit?,
         display-unit?,
         energy-unit?,
         current-rung?,
         decimal-character?)
    >

    <!ATTLIST preferences
        version     CDATA   #REQUIRED
    >

    <!ELEMENT log-unit              (#PCDATA)>
    <!ELEMENT display-unit          (#PCDATA)>
    <!ELEMENT energy-unit           (#PCDATA)>
    <!ELEMENT current-rung          (#PCDATA)>
    <!ELEMENT decimal-character     (#PCDATA)>

    <!-- Diet plan.  This element is optional but,
         if present, must be after the preferences,
         if present.  -->

    <!ELEMENT diet-plan
        (calorie-balance?,
         start-weight?,
         goal-weight?,
         start-date?,
         show-plan?)
    >

    <!ATTLIST diet-plan
        version     CDATA   #REQUIRED
    >

    <!ELEMENT calorie-balance       (#PCDATA)>
    <!ELEMENT start-weight          (#PCDATA)>
    <!ELEMENT goal-weight           (#PCDATA)>
    <!ELEMENT start-date            (#PCDATA)>
    <!ELEMENT show-plan             (#PCDATA)>

    <!-- Monthly log.  Any number of monthly logs may
         appear, in any order. -->

    <!ELEMENT monthlog
        (properties, days)
    >

    <!ATTLIST monthlog
        version     CDATA   #REQUIRED
    >

    <!ELEMENT properties
        (year,
         month,
         weight-unit,
         trend-carry-forward?,
         last-modified?)
    >

    <!ELEMENT year                  (#PCDATA)>
    <!ELEMENT month                 (#PCDATA)>
    <!ELEMENT weight-unit           (#PCDATA)>
    <!ELEMENT trend-carry-forward   (#PCDATA)>
    <!ELEMENT last-modified         (#PCDATA)>

    <!ELEMENT days
        (day+)
    >

    <!ATTLIST days
        ndays       CDATA   #REQUIRED
    >

    <!ELEMENT day
        (date,
         weight,
         rung,
         flag,
         comment)
    >

    <!ELEMENT date                  (#PCDATA)>
    <!ELEMENT weight                (#PCDATA)>
    <!ELEMENT rung                  (#PCDATA)>
    <!ELEMENT flag                  (#PCDATA)>
    <!ELEMENT comment               (#PCDATA)>

=== Fourmilab/hackers_diet_online/webdoc/images/2007-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="https://www.fourmilab.ch/hackdiet/online/hackdiet_db.css"?>
<!DOCTYPE hackersdiet SYSTEM
        "https://www.fourmilab.ch/hackdiet/online/hackersdiet.dtd">
<hackersdiet version="1.0">
    <epoch>2007-04-28T19:34:43Z</epoch>
    <account version="1.0">
        <user version="1.0">
            <login-name>Example</login-name>
            <first-name>Example</first-name>
            <middle-name>J.</middle-name>
            <last-name>Account</last-name>
            <e-mail>chef@ratburger.org</e-mail>
            <height>180</height>
            <account-created>2007-04-24T19:46:38Z</account-created>
        </user>
        <preferences version="1.0">
            <log-unit>kilogram</log-unit>
            <display-unit>kilogram</display-unit>
            <energy-unit>calorie</energy-unit>
            <current-rung>0</current-rung>
            <decimal-character>.</decimal-character>
        </preferences>
        <diet-plan version="1.0">
            <calorie-balance>-500</calorie-balance>
            <start-weight>85</start-weight>
            <goal-weight>75</goal-weight>
            <start-date>2006-03-15T00:00:00Z</start-date>
            <show-plan>1</show-plan>
        </diet-plan>
    </account>
    <monthlogs version="1.0">
    <monthlog version="1.0">
        <properties>
            <year>2007</year>
            <month>2</month>
            <weight-unit>kilogram</weight-unit>
            <trend-carry-forward>75.0163</trend-carry-forward>
            <last-modified>2007-04-28T19:34:15Z</last-modified>
        </properties>
        <days ndays="28">
            <day>
                <date>1</date>
                <weight>75.2</weight>
                <rung>36</rung>
                <flag></flag>
                <comment></comment>
            </day>
            <day>
                <date>2</date>
                <weight>73.8</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment></comment>
            </day>
            <day>
                <date>3</date>
                <weight>75.9</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment>London</comment>
            </day>
            <day>
                <date>4</date>
                <weight>74.2</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment>&#x41c;&#x43e;&#x441;&#x43a;&#x432;&#x430;</comment>
            </day>
            <day>
                <date>5</date>
                <weight>74.3</weight>
                <rung>36</rung>
                <flag></flag>
                <comment>&#x41c;&#x43e;&#x441;&#x43a;&#x432;&#x430;</comment>
            </day>
            <day>
                <date>6</date>
                <weight>76.3</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment>&#x6771;&#x4eac;</comment>
            </day>
            <day>
                <date>7</date>
                <weight>75.8</weight>
                <rung>36</rung>
                <flag></flag>
                <comment>&#x6771;&#x4eac;</comment>
            </day>
            <day>
                <date>8</date>
                <weight>75.1</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment>&#x5e73;&#x58e4;&#x76f4;&#x8f44;&#x5e02;</comment>
            </day>
            <day>
                <date>9</date>
                <weight>74.5</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment>&#x5e73;&#x58e4;&#x76f4;&#x8f44;&#x5e02;</comment>
            </day>
            <day>
                <date>10</date>
                <weight>74.7</weight>
                <rung>36</rung>
                <flag></flag>
                <comment>&#x5e73;&#x58e4;&#x76f4;&#x8f44;&#x5e02;</comment>
            </day>
            <day>
                <date>11</date>
                <weight>75</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment>&#x62a;&#x647;&#x631;&#x627;&#x646;</comment>
            </day>
            <day>
                <date>12</date>
                <weight>74</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment>&#x62a;&#x647;&#x631;&#x627;&#x646;</comment>
            </day>
            <day>
                <date>13</date>
                <weight>75.5</weight>
                <rung></rung>
                <flag></flag>
                <comment>&#x637;&#x631;&#x627;&#x628;&#x644;&#x633;</comment>
            </day>
            <day>
                <date>14</date>
                <weight>74.3</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment>&#x637;&#x631;&#x627;&#x628;&#x644;&#x633;</comment>
            </day>
            <day>
                <date>15</date>
                <weight>74.5</weight>
                <rung></rung>
                <flag></flag>
                <comment>Gen&#xe8;ve</comment>
            </day>
            <day>
                <date>16</date>
                <weight>73.9</weight>
                <rung>36</rung>
                <flag></flag>
                <comment></comment>
            </day>
            <day>
                <date>17</date>
                <weight>74.1</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment></comment>
            </day>
            <day>
                <date>18</date>
                <weight>75.6</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment></comment>
            </day>
            <day>
                <date>19</date>
                <weight>74.6</weight>
                <rung>36</rung>
                <flag></flag>
                <comment></comment>
            </day>
            <day>
                <date>20</date>
                <weight>75.3</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment></comment>
            </day>
            <day>
                <date>21</date>
                <weight>74.8</weight>
                <rung>36</rung>
                <flag></flag>
                <comment></comment>
            </day>
            <day>
                <date>22</date>
                <weight>74.5</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment></comment>
            </day>
            <day>
                <date>23</date>
                <weight>75.4</weight>
                <rung>36</rung>
                <flag></flag>
                <comment></comment>
            </day>
            <day>
                <date>24</date>
                <weight>74.9</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment></comment>
            </day>
            <day>
                <date>25</date>
                <weight>75</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment></comment>
            </day>
            <day>
                <date>26</date>
                <weight>74.9</weight>
                <rung>36</rung>
                <flag></flag>
                <comment></comment>
            </day>
            <day>
                <date>27</date>
                <weight>75.4</weight>
                <rung>36</rung>
                <flag>1</flag>
                <comment></comment>
            </day>
            <day>
                <date>28</date>
                <weight>75.3</weight>
                <rung>36</rung>
                <flag></flag>
                <comment></comment>
            </day>
        </days>
    </monthlog>
    </monthlogs>
</hackersdiet>
